--- h5py-2.8.0.orig/h5py/_errors.pyx	2018-05-13 21:33:33.000000000 -0300
+++ h5py-2.8.0/h5py/_errors.pyx	2018-10-22 14:50:56.674025360 -0300
@@ -73,6 +73,13 @@
     (H5E_SYM, H5E_CANTINIT):        ValueError, # Object already exists/1.8
     (H5E_ARGS, H5E_BADTYPE):        ValueError, # Invalid location in file
     (H5E_REFERENCE, H5E_CANTINIT):  ValueError, # Dereferencing invalid ref
+    
+    # needed for 1.10.3 to maintain compatibility with 1.10.{0,1,2}
+    
+    # due to changes to H5Gdeprec.c:H5Gget_num_objs
+    (H5E_SYM, H5E_BADTYPE):         ValueError, # Invalid location in file
+    # due to changes to H5F.c:H5Fstart_swmr_write
+    (H5E_FILE, H5E_CANTCONVERT):    ValueError, # Invalid file format
   }
 
 cdef struct err_data_t:
